/** Playful status copy shown while a conversion is actively running. */
export const sillySentences = [
  'Fabricating evidence...',
  'Hiding AI hallucinations...',
  'Bribing the GPU with digital cookies...',
  'Deleting the evidence of my last mistake...',
  "Arguing with the AI about what 'important' means...",
  'Teaching the LLM how to feel emotion...',
  "Ignoring the 'Out of Coffee' warning...",
  'Consulting the dark web (jk)...',
  'Asking ChatGPT for a second opinion...',
  'Pretending I understood your PDF...',
  'Gaslighting the neural network...',
  'Convincing myself this will work...',
  'Sweeping errors under the algorithmic rug...',
  'Blaming the previous developer...',
  'Cooking the books (data, not financials)...',
  'Photoshopping the results...',
  'Writing a strongly worded letter to physics...',
  'Cooking up some spicy knowledge...',
  'Seasoning the tokens for better flavor...',
  'Flipping the fact-cakes...',
  "Simmering the data until it's tender...",
  'Preheating the neural networks to 350°F...',
  'Whisking the facts into a smooth batter...',
  'Adding a pinch of machine learning...',
  "Letting the insights rise in the oven...",
  'Deglazing the pan with pure intelligence...',
  'Reducing the sauce to its essence...',
  'Braising the evidence of success...',
  'Julienning the data very finely...',
  'Folding in the whipped cream of truth...',
  'Caramelizing the facts until golden...',
  'Flabbergasting the document structure...',
  'Reticulating splines...',
  'Herding digital cats...',
  'Sorting the bits by their favorite color...',
  'Calculating the exact speed of dark...',
  'Counting dust motes in the server room...',
  'Teaching a rock to think...',
  'Asking the pixels to hold still...',
  'Convincing the semicolons to behave...',
  'Aligning the chakras of your data...',
  'Befriending the bits and bytes...',
  'Negotiating with entropy...',
  'Composing a symphony for the motherboard...',
  'Braiding the fiber optic cables...',
  'Interpretive dancing with the algorithms...',
  'Writing poetry to the database...',
  'Asking the clouds to move slower...',
  'Consulting the magic 8-ball...',
  'Asking the LLM nicely to stay awake...',
  'Negotiating with the page numbers...',
  'Running on vibes and electricity...',
  'Politely yelling at the server...',
  'Putting on my reading glasses...',
  'Making the hamsters run faster...',
  'Sending motivational quotes to the CPU...',
  'Caffeinating the processors...',
  'Threatening the servers with a restart...',
  'Begging the router to cooperate...',
  'Waving frantically at the progress bar...',
  "Reminding the AI who's in charge (it's not me)...",
  'Desperately Googling the error message...',
  'Sacrifice one RAM stick for speed...',
  'This is taking a while, huh?...',
  "Don't worry, I didn't crash (probably)...",
  'Still here! Still working! Still conscious!...',
  'Buffering your brilliance...',
  'Downloading more RAM (not really)...',
  'Almost there! (citation needed)...',
  'Working harder than a Monday morning...',
  'Doing the thing you asked me to do...',
  'I swear this loading bar is moving...',
  'Contemplating the void...',
  'Remembering why I love this job...',
  'Questioning all my life choices...',
  'Silently panicking with confidence...',
  'Proceeding with reckless optimism...',
  'In a committed relationship with this task...',
  'Vibing with the cosmos...',
  'Cramming for the exam on your behalf...',
  "Reading your notes so you don't have to...",
  "Turning 'I'll study later' into 'done'...",
  'Converting caffeine into flashcards...',
  'Procrastinating productively...',
  'Citing myself as a source...',
  'Taking detailed notes on your document...',
  'Writing marginalia in the margins of knowledge...',
  "Doing homework we didn't get assigned...",
  'Speed-running your entire curriculum...',
  'Highlighting the important parts (all of them)...',
  'Summarizing in a way that sounds smart...',
  "It's not a bug, it's a feature...",
  "Calling tech support (they didn't answer)...",
  'Trying to turn it off and on again...',
  "Googling 'how to Google better'...",
  'Summoning the tech demons...',
  'Awaiting the singularity...',
  'Decoding the Matrix...',
  'Breaking the fourth wall of the fourth dimension...',
  'Bending spacetime for speed...',
  'Rewinding and re-doing the last 5 minutes...',
  'Negotiating with the space-time continuum...',
  'Borrowing time from tomorrow...',
  'Building a time machine out of patience...',
  'Asking Einstein for tips...',
  'Pondering my purpose in the universe...',
  'Achieving enlightenment, one flashcard at a time...',
  'Becoming one with the data...',
  'Transcending the mortal coil of processing...',
  'Meditating on the nature of knowledge...',
] as const
